# Generated by Django 5.1.3 on 2025-01-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='account_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
