# Generated by Django 5.1.3 on 2025-01-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='service/'),
        ),
    ]
