# Generated by Django 5.1.3 on 2025-01-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0002_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(help_text='Short subtitle for the slider', max_length=255)),
                ('title', models.CharField(help_text='Main title for the slider', max_length=255)),
                ('paragraph', models.TextField(help_text='Description paragraph for the slider')),
                ('btntext', models.TextField(help_text='Button text for the slider')),
                ('contact_number', models.CharField(help_text='Contact number to display', max_length=20)),
                ('contact_link', models.URLField(help_text="Link for the 'Describe More' button")),
                ('background_image', models.ImageField(help_text='Background image', upload_to='slider/backgrounds/')),
                ('slider_image', models.ImageField(help_text='Main image for the slider', upload_to='slider/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
