# Generated by Django 5.1.3 on 2025-01-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0003_slidersection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(help_text='Short subtitle for the slider', max_length=255)),
                ('title', models.CharField(help_text='Main title for the slider', max_length=255)),
                ('paragraph', models.TextField(help_text='Description paragraph for the slider')),
                ('btntext', models.TextField(help_text='Button text for the slider')),
                ('list_one', models.CharField(help_text='Contact number to display', max_length=20)),
                ('list_two', models.CharField(help_text='Contact number to display', max_length=20)),
                ('list_three', models.CharField(help_text='Contact number to display', max_length=20)),
                ('name', models.CharField(help_text='Contact number to display', max_length=20)),
                ('job', models.CharField(help_text='Contact number to display', max_length=20)),
                ('background_image', models.ImageField(help_text='Background image', upload_to='slider/backgrounds/')),
                ('slider_image', models.ImageField(help_text='Main image for the slider', upload_to='slider/images/')),
                ('profile', models.ImageField(help_text='Main image for the slider', upload_to='slider/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
