# Generated by Django 5.1.3 on 2025-01-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0004_aboutsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='job',
            field=models.CharField(help_text='Contact number to display', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='name',
            field=models.CharField(help_text='Contact number to display', max_length=20, null=True),
        ),
    ]
