# Generated by Django 5.1.3 on 2025-01-03 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0005_alter_aboutsection_job_alter_aboutsection_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.ImageField(null=True, upload_to='service/')),
                ('after', models.ImageField(null=True, upload_to='service/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('link1', models.CharField(max_length=255)),
                ('link2', models.CharField(max_length=255)),
                ('link3', models.CharField(max_length=255)),
                ('link4', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='service/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('paragraph', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='service/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headerone', models.CharField(max_length=255)),
                ('headertwo', models.CharField(max_length=255)),
                ('headerthree', models.CharField(max_length=255)),
                ('paragraphone', models.CharField(max_length=255)),
                ('paragraphtwo', models.CharField(max_length=255)),
                ('paragraphthree', models.CharField(max_length=255)),
                ('imageone', models.ImageField(null=True, upload_to='service/')),
                ('imagetwo', models.ImageField(null=True, upload_to='service/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
