# Generated by Django 5.1.3 on 2025-01-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0006_beforeafter_book_team_testimonial_whychoose'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychoose',
            name='header',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whychoose',
            name='paragraph',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
