# Generated by Django 5.1.3 on 2025-01-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
