# Generated by Django 5.1.3 on 2025-01-06 06:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0013_alter_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailone', models.CharField(max_length=255)),
                ('emailtwo', models.CharField(max_length=255)),
                ('phoneone', models.CharField(max_length=255)),
                ('phonetwo', models.CharField(max_length=255)),
                ('addressone', models.CharField(max_length=255)),
                ('addresstwo', models.CharField(max_length=255)),
                ('workday', models.CharField(max_length=255)),
                ('worktime', models.CharField(max_length=255)),
                ('socialtext', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('footertext', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
