# Generated by Django 5.1.3 on 2025-01-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0014_contactaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactaddress',
            name='socialtext',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
