# Generated by Django 5.1.3 on 2025-01-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0015_alter_contactaddress_socialtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactaddress',
            name='socialtext',
            field=models.TextField(null=True),
        ),
    ]
